# Generated by Django 3.1.3 on 2020-11-25 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('phone', models.CharField(blank=True, help_text='example:09121112020', max_length=11, null=True, validators=[profiles.models.VALID])),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('c', 'Costum'), ('p', 'Prefer Not To Say')], default='m', max_length=20)),
                ('birthday', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
