# Generated by Django 3.1.3 on 2020-11-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201129_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='avatar',
            field=models.ImageField(default='/static/images/no.png', upload_to='avatar'),
        ),
    ]
