# Generated by Django 3.1.3 on 2020-12-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201129_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='avatar',
            field=models.ImageField(default='./static/images/no.png', upload_to='avatar'),
        ),
    ]
