# Generated by Django 3.1.3 on 2020-12-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201202_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_information',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
