# Generated by Django 3.1.3 on 2020-11-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(default='static/images/no.png', upload_to='image'),
        ),
    ]
